using Modules.O.M.A.Games.GDOrganizer.DataStructs;
using O.M.A.Games.GDOrganizer.Generated;
using Plugins.O.M.A.Games.GDOrganizer.Runtime.Utils;
using Plugins.O.M.A.Games.GDOrganizer.Runtime.Entity;
using UnityEngine;

namespace O.M.A.Games.GDOrganizer.GameDesignDefinition
{
	/// <summary>
	/// This class template has been generated.
	/// You can add your custom code within the class body.
	/// As long as the file is present it won't be overwritten
	
	/// NOTE: If you want to regenerate this file you have to delete it and press regenerate.
	/// ----------------------------------------------------------------------------------------------------
	
	///This class template has been generated by 'EntityDefinitionGenerator'
	/// </summary>
	public class StorableDefinition : ScriptableObject, IEntityDefinition
	{
		private const EntityProperty Component = EntityProperty.Storable;
		[SerializeField, ReadOnly]
		private EntityType _entityType;
		public EntityType EntityType => _entityType;
		
		// Put in your custom code here ...
		public StorableConfig Config;
#if UNITY_EDITOR
		public void OnValidate()
		{
			if (Config.EntityType != EntityType.None && Config.EntityType != EntityType.Invalid)
			{
				return;
			}
			Regenerate();
		}
		[ContextMenu("Regenerate")]
		public void Regenerate()
		{
			Config = new StorableConfig()
			{
				EntityType = _entityType,
				EntityProperty = Component,
				VolumePerUnit = Random.Range(1, 30),
				WeightPerUnit = Random.Range(1, 30)
			};
		}
		public void SetEntityType(EntityType type)
		{
			_entityType = type;
		}
#endif
	}
}
